Feature/beregn saertilskudd feature
navikt/bidrag-cucumber-cloud pull request #152
Opened 2021-12-22 10:13 UTC by bragejahren

* Lagt inn `saertilskudd.feature`

2021-12-22 10:24 UTC, jactor-rises requested changes
Denne klassen må inn i pakken `.../cloud/beregn`
https://github.com/navikt/bidrag-cucumber-onprem/blob/main/src/main/kotlin/no/nav/bidrag/cucumber/onprem/beregn/BeregnEgenskaper.kt

og samtlige tester i feature-fil bør flyttes over

2021-12-22 10:28 UTC, jactor-rises commented
I tillegg bør du legge inn jobben i nattlig kjøring: https://github.com/navikt/bidrag-cucumber-cloud/blob/main/.github/workflows/run-nightly.yaml

2021-12-23 07:08 UTC, bragejahren commented
Da har jeg flyttet alt som omhandler saertilskudd fra `cucumber-onprem` inn hit, og lagt testing av saertilskudd inn i nattlig jobb

2021-12-23 07:40 UTC, jactor-rises approved these changes
👍🏻

2021-12-23 08:55 UTC, merged